### ISSUE TITLE
Signer About Page Link Action

### ISSUE THREAD

**Issue by stechu** [Manta-Network/manta-signer#137]
In the current about page, opening the link will display the github page inside the signer (and there is no way of going back).
<img width="345" alt="Screen Shot 2022-07-08 at 10 23 25 AM" src="https://user-images.githubusercontent.com/720571/178040676-16a662d3-8510-4e1b-a59d-907ab00733c7.png">

It should open a link (link to documentation ideally) in the browser rather than inside of signer.

**Comment by Kevingislason** [comment]
Seems to work as expected now
