### ISSUE TITLE
Bump tauri to mitigate CVEs

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/manta-signer#226]
Manta-signer is using [1.0.2](https://github.com/Manta-Network/manta-signer/blob/main/ui/src-tauri/Cargo.toml#L42), but there're two CVEs from tauri, so we better to bump tauri.
https://github.com/advisories/GHSA-28m8-9j7v-x499
https://github.com/advisories/GHSA-q9wv-22m9-vhqh
https://github.com/advisories/GHSA-6mv3-wm7j-h4w5

**Comment by Apokalip** [comment]
CVEs do not affect us, not worth the update when we are deprecating soon
