### ISSUE TITLE
manta-signer: error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by bmaciag** [Manta-Network/manta-signer#238]
Hi, just installed manta-signer on Ubuntu via:
`sudo apt -y install ./manta-signer-ubuntu-18.04_1.0.0_amd64.deb`
now when I run manta-signer I get the following error:
`manta-signer: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
Any idea?

I already tired:
`sudo apt install openssl`
But this was already installed.

**Comment by stechu** [comment]
@Apokalip

**Comment by Apokalip** [comment]
> 

Just to confirm, the machine you are trying to install this is running on Ubuntu 18.04 right?

**Comment by bmaciag** [comment]
Just started with a fresh 22.04 and retired with the 22.04 release and it works.
