### ISSUE TITLE
The first character of secret recovery phase should not be upper case.

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/manta-signer#275]
If I choose to recovery my zk account, the first char of each of secret recovery phase will be come upper case when I finish input.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/1914204/215300926-4d4ddc0f-89a5-4b23-81dc-414222322136.png">

It's not that friendly. I have go back to make this char lower case. But not sure it's input method problem(I'm on Mac).

**Comment by Apokalip** [comment]
This is a mac thing, it tries to capitalize your first word to make typing easier. Mac option for text input not available on other oses
