### ISSUE TITLE
Communicate Version Number to Frontend

### ISSUE THREAD

**Issue by bhgomes** [Manta-Network/manta-signer#34]
- [ ] Send signer version number on all communication with frontend
- [ ] Make sure all versions are actually done properly. Here's a badly done version number (it should be `VERSION` not `0.0.0`): https://github.com/Manta-Network/manta-signer/blob/1157e0a917ad77bf6d2546adec5c3a8c177d74e4/src/service.rs#L508-L527

**Comment by dansofter** [comment]
I think we can modify the signer to return the version number inside `heartbeat` endpoint, in which we are currently returning `heartbeat` string.
This sounds like the fasted solution.
@bhgomes @tommyjk21 @Kevingislason

**Comment by bhgomes** [comment]
> I think we can modify the signer to return the version number inside `/heartbeat` endpoint, in which we are currently returning `heartbeat` string.
> 
> This sounds like the fasted solution.
> 
> @bhgomes @tommyjk21 @Kevingislason 

Yes that's the first checkbox above.

**Comment by dansofter** [comment]
We will still need to add a method to fetch version number to the signer client and signer interface.
